### ISSUE TITLE
Incorrect Status Labels

### ISSUE THREAD

**Issue by My-Random-Thoughts** [bill-ahmed/qbit-matUI#100]
**Describe the bug**
The status labels for "Moving" and "Seeding" show "Unknown" and "Stalled" respectively.

**To Reproduce**
1. Have one or more torrents either moving or seeding
2.  
3. 

**Expected behavior**
Correct labels should be shown

**Actual behavior**
The status labels for "Moving" and "Seeding" show "Unknown" and "Stalled" respectively.

**Screenshots**
![Correct](https://user-images.githubusercontent.com/21334396/102280469-1b57a280-3f25-11eb-8c31-d6ae3a402bc0.png)
![Wrong](https://user-images.githubusercontent.com/21334396/102280472-1bf03900-3f25-11eb-8a29-2cbfd287d638.png)

**Desktop (please complete the following information):**
 - Browser: Chromium
 - Build:   Ubuntu 20.04
 - Version: v1.10.1 .

**Additional info**
Thanks for your hard work :)

**Comment by bill-ahmed** [comment]
Those labels have been bothering me for some time! I'll go ahead an queue that up

**Comment by bill-ahmed** [comment]
Changes will appear in the next release `1.10.2`!
