### ISSUE TITLE
Add ability to config and see alternative speeds

### ISSUE THREAD

**Issue by IevgenSobko** [bill-ahmed/qbit-matUI#104]
Default web-ui contains an ability to configure and see currently applied speed limits.
It would be great to have the same functionality with this UI.
Could you please add the ability to configure and see alternative speeds?
It is useful to enable alternative speeds for working hours.

Here is example of configuration from default UI
![2021-01-07__11-50-13](https://user-images.githubusercontent.com/14232100/103878210-c865ab00-50de-11eb-84a9-214828446954.png)

And this is the footer part that allows you to understand that you have alternative speeds enabled (first icon) and actually applied speeds (numbers in square brackets)
![2021-01-07__11-53-29](https://user-images.githubusercontent.com/14232100/103878371-02cf4800-50df-11eb-95b9-e6cc0a604ebd.png)

**Comment by bill-ahmed** [comment]
I've been meaning to refactor that general info shown underneath the torrent table for a while now, that PR will include the feature to view alternate rate limits and toggle it.

**Comment by IevgenSobko** [comment]
Great to hear that. Looking for the next release to try.

**Comment by bill-ahmed** [comment]
Still waiting on #106 to get merged.
