### ISSUE TITLE
Noob webdeveloper here (first couple months of programming school). I would like to try to turn the dark mode into dracula mode.

### ISSUE THREAD

**Issue by Pistrie** [bill-ahmed/qbit-matUI#110]
I've done basically no webdesign yet, so I wanted to try something out.
Could you give me some pointers on which color values to change? I took a quick look and saw that the /app directory has some subfolders which contain .scss files. Would only changing these files be enough?

Sorry if this is a dumb question :)

**Comment by bill-ahmed** [comment]
Hey, so there are a couple files you'll want to take a look at. As a note before you start, the styling is a bit of a mess atm...i'm hoping to improve this in the near future (such as by adding support for an arbitrary number of themes) although am currently preoccupied with school.

The theming process makes use of Angular Material's mat-core, you can find out more on the [official docs](https://material.angular.io/guide/theming#theming-your-own-components), as well as this handy [medium article](https://medium.com/@tomastrajan/the-complete-guide-to-angular-material-themes-4d165a9d24d1).
The styles for light/dark themes are located in: `src/variables.scss`, and these get loaded into `src/theme.scss`. The dark theme in particular is defined under the `dark-theme` css class, on line 18. You should be able to modify the values of `$dark-primary`, `$dark-accent`, etc. in `variables.scss`
