### ISSUE TITLE
Maybe not a bug?  Unacceptable file type

### ISSUE THREAD

**Issue by Brodieman** [bill-ahmed/qbit-matUI#111]
Might not be a bug but I am looking for help.  I have qBittorrent running on a NAS and I access it via the webui and I was looking to change the UI.  When I point the Alt UI to your folder I get the error "Unacceptable file type, only regular file is allowed."  I have tried the path several ways pointing to several different folders\files.

Thanks for any help!

**Comment by bill-ahmed** [comment]
Hi, the issue might be related to an older version of qBittorrent.

The release ZIP files contain two folders: `public/` and `private/`. On older versions of qBittorrent it would try and look for a file named `login.html` inside `public/`. Try changing `index.html` to `login.html`.

**Comment by Brodieman** [comment]
Same result

**Comment by bill-ahmed** [comment]
Great, next time please also remember to use the bug template provided 🙂.

**Comment by Brodieman** [comment]
OK, sorry.  I figured it was NOT a bug so I didn't fill it out like that.
