### ISSUE TITLE
[BUG] Skin not loading icons

### ISSUE THREAD

**Issue by Ansem93** [bill-ahmed/qbit-matUI#114]
**Describe the bug**
On qBittorrent installed via docker it can't load icons
![immagine](https://user-images.githubusercontent.com/6626218/113477978-37586300-9486-11eb-91cb-2137b0bbe181.png)
![immagine](https://user-images.githubusercontent.com/6626218/113478002-61aa2080-9486-11eb-95aa-57cd5ae91f1f.png)

**To Reproduce**
1. I put the skin inside the download folder as a test
2. Made qBittorrent point to download/MatUI

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Build:   windows 10
 - Version: v. 1.11

**Comment by bill-ahmed** [comment]
Hey sorry about the late reply, can you provide the browser logs? Open the developer console and send a screenshot of the errors.

**Comment by Ansem93** [comment]
I solved it after reading the errors. For some reason firefox privacy mode will block all the images. Did they come from some third party sites?

**Comment by bill-ahmed** [comment]
Yup, some fonts and material icons are downloaded from Google Fonts (`fonts.gstatic.com`). If Firefox is blocking those then it would explain the missing icons issue. I'll look into saving the fonts locally as part of the bundle, so in the future it shouldn't rely on any 3rd-party sites.

Glad you were able to solve it!

**Comment by bill-ahmed** [comment]
Closing this issue as it's been resolved.

**Comment by Ansem93** [comment]
That would be great. I too usually block everything related to google with ublock origin for privacy reason :)
