### ISSUE TITLE
Mobile Web-UI?

### ISSUE THREAD

**Issue by HetBalderdier** [bill-ahmed/qbit-matUI#119]
Hello, is it possible to add a mobile Web-UI for viewing on Android browser?

**Comment by bill-ahmed** [comment]
It is possible to access it via a web browser on android (e.g. Chrome), and for the best experience I would recommend enabling "Desktop site". I'm not sure if that's what you were asking, did you mean something like a mobile app instead?

**Comment by bill-ahmed** [comment]
> It is possible to access it via a web browser on android (e.g. Chrome), and for the best experience I would recommend enabling "Desktop site". I'm not sure if that's what you were asking, did you mean something like a mobile app instead?

To add to this, I am continually trying to make the mobile browser experience better over time. The biggest issue is the torrent table which doesn't have a neat way of fitting into a small display :(

**Comment by HetBalderdier** [comment]
Yes, I am talking about mobile browsing experience, not an app. Putting my mobile browser in 'Desktop Site' makes the experience better but not perfect. I'm glad to hear you're working on it and I'm looking forward to the solution
