### ISSUE TITLE
Support registration of magnet links via web client

### ISSUE THREAD

**Issue by majkinetor** [bill-ahmed/qbit-matUI#130]
You can enable this on default Web UI

![image](https://user-images.githubusercontent.com/85767/130330635-8e08ce37-a4b1-40b9-bf6b-b9e23f1e8322.png)

Then when you click magnet link it opens automatically 

![image](https://user-images.githubusercontent.com/85767/130330653-991ac366-a383-4c22-bd84-37899aedac30.png)

However when you I switch to matUI i only get long URL with magnet and nothing happens

**Comment by bill-ahmed** [comment]
I'm not too familiar with this feature in qBittorrent, i'll look into it and see what I find.

**Comment by bill-ahmed** [comment]
Alright, it looks pretty straight forward. @majkinetor do keep in mind that it will only work over HTTPS, given the browser supports it.

**Comment by majkinetor** [comment]
Yeah, I know. I used mkcert to create self signed cert and then it worked.

**Comment by bill-ahmed** [comment]
This should be fixed in the latest release (`v1.13.0`). @majkinetor if you can confirm it is indeed working and close this issue, thanks :)

**Comment by majkinetor** [comment]
Yes, it works. However, the one must first run original UI to enable the option, then switch to matUI to use it. It would be great to make option available too, for example:

![image](https://user-images.githubusercontent.com/85767/132092273-5e499a05-6bdb-47e5-bc61-49e8200854e3.png)

**Comment by bill-ahmed** [comment]
The option is available, under the Web UI settings (check the release notes)!

**Comment by majkinetor** [comment]
Ah, sorry, didn't notice it. 

OK, its done then. Thank you.
