### ISSUE TITLE
I would like the column header category to be able to see

### ISSUE THREAD

**Issue by Brodieman** [bill-ahmed/qbit-matUI#144]
I would like to be able to add the column of category.  I use categories often.

**Comment by bill-ahmed** [comment]
I'll try and get a PR up with a bunch more columns. It's hard to tell what others use, so thanks for opening up an issue :)

**Comment by Brodieman** [comment]
No problem!  Liked the skin, thanks.  I have a (pretty impressive if I do say) PowerShell script that I (poorly but it works) wrote that runs after a torrent is done in qBittorrent which relies on the categories.
