### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Csineneo** [bill-ahmed/qbit-matUI#149]
1. Custom date format, my preferred format is yyyy-mm-dd HH:MM:SS, which is shorter and saves space.
2. Custom theme color. Blue is good, but I like pink ☺️
3. Tracker filter, by domain, and avoid show BT tracker
4. Tracker column, tracker's domain only. This is very useful if you have many private trackers.
5. Is it possible to implement the statistics function? Uptime, cumulative uploaded/downloaded bytes ...

Screenshot for reference:
<img width="285" alt="image" src="https://user-images.githubusercontent.com/1370009/142583731-af9c27fb-6f09-473a-a0fd-bcc163756752.png">

**Comment by bill-ahmed** [comment]
Thanks for opening an issue. That's certainly a lot of requests, we'll have to break them down into separate issues to better track them.

I can't guarantee that I can tackle all of the points mentioned, will give it a shot when I have some time.

**Comment by bill-ahmed** [comment]
@Csineneo if you could open separate feature requests for each of the points above ^

**Comment by Csineneo** [comment]
These have been split into separate issues.
