### ISSUE TITLE
Download locations

### ISSUE THREAD

**Issue by ahkaroly** [bill-ahmed/qbit-matUI#150]
**Describe the bug**
Probably not a Bug, I just don't figure out how to.

**To Reproduce**
I can't create a folder for download locations because I can't see the drives.
What am I ruining?
Thank you very much for your help!

**Screenshots**
http://gofile.me/5pdzC/jILw0lErd

**Desktop**
 - Browser: [Google Chrome]
 - Build:   [Windows]
 - Version: [1.16.1]

**Comment by ahkaroly** [comment]
Sorry, my question is irrelevant. I downloaded it again and now it's good :)

Just one more question, can you view the folders on an existing drive?

**Comment by bill-ahmed** [comment]
Hi, that folder view is not the complete picture. All of those folders are populated based on the torrents you have downloaded. 

So as you download more torrents, and in more unique places, those folders will begin to show up. Hope that clears things up.

**Comment by bill-ahmed** [comment]
Closing as it seems to be resolved.
