### ISSUE TITLE
Add tracker column

### ISSUE THREAD

**Issue by Csineneo** [bill-ahmed/qbit-matUI#153]
**Describe the solution you'd like**
Tracker column, tracker's domain only. This is very useful if you have many private trackers.

**Additional context**
<img width="149" alt="image" src="https://user-images.githubusercontent.com/1370009/143195214-a57cca63-6152-43f7-9abc-41cb43747b62.png">

**Comment by sbach89** [comment]
Any way to see trackers would be nice. Checking 'info' on a torrent doesn't even list them.
