### ISSUE TITLE
Statistics function

### ISSUE THREAD

**Issue by Csineneo** [bill-ahmed/qbit-matUI#155]
**Describe the solution you'd like**
Is it possible to implement the statistics function? Uptime, cumulative uploaded/downloaded bytes ...

**Additional context**
<img width="287" alt="image" src="https://user-images.githubusercontent.com/1370009/143195779-56db1192-de3d-43a3-b7b1-b3204d1258f9.png">

**Comment by bill-ahmed** [comment]
The default Web UI has the following "statistics" available:

![image](https://user-images.githubusercontent.com/45879053/143264860-f6e5efb3-59f5-4250-b048-fbac2054a64c.png)

Aside from this, there isn't much other data provided by qBittorrent.
