### ISSUE TITLE
Download location list selection

### ISSUE THREAD

**Issue by Csineneo** [bill-ahmed/qbit-matUI#156]
**Describe the solution you'd like**
The download location can be selected from the locations of existing tasks

**Additional context**
<img width="549" alt="image" src="https://user-images.githubusercontent.com/1370009/143197369-49058f10-eaac-4523-815d-bc105207b7bc.png">

**Comment by bill-ahmed** [comment]
If this is just a dropdown of all save locations, then it's certainly doable. This Web UI actually allows you to explore a pseudo "file system" of all downloaded torrents, not sure if that's helpful here.

@Csineneo Also, which Web UI are you currently using? It would be helpful to know so I can better understand the feature requests.

**Comment by Csineneo** [comment]
> If this is just a dropdown of all save locations, then it's certainly doable

Yes.

> which Web UI are you currently using?

It's [transmission web control](https://github.com/ronggang/transmission-web-control).
Transmission is not stable enough and there are some performance issue. I have been considering switching to to qbittorrent but the ugly webui stopped me until I found yours.
