### ISSUE TITLE
Unacceptable file type only regular file is allowed.

### ISSUE THREAD

**Issue by Hazma314** [bill-ahmed/qbit-matUI#162]
**Describe the bug**
Web UI on qbittorrent 4.1.7 will display "Unacceptable file type only regular file is allowed." when pointed at unzipped Unix release 1.16.2

**To Reproduce**
1. Download and unzip release 1.16.2 for Unix
2.  Follow steps as listed in the readme
3. Observe webpage

**Expected behavior**
Page Appears

**Actual behavior**
Text reading "Unacceptable file type only regular file is allowed." appears

**Desktop (please complete the following information):**
 - Browser: Firefox 95.0.1 64 Bit
 - Build:   Linux Mint 20.0.2 Cinnamon
 - Version: 1.16.2

**Additional info**
Solution ended up being renaming "index.html" in the public folder to "login.html". Posting this here in case other people run into the same problem, took me a while to find forum posts about similar issues with a solution that worked.

**Comment by bill-ahmed** [comment]
This looks to be an issue with older versions of qBittorrent. Thanks for pointing out the solution that worked for you, i'll keep this pinned in case anyone else has the same problem.
